# Generated by Django 5.0.6 on 2024-06-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorous', models.FloatField()),
                ('potassium', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CropYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('annual_rainfall', models.CharField(max_length=100)),
                ('fertilizer_usage', models.CharField(max_length=100)),
                ('pesticide_usage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_color', models.CharField(max_length=100)),
                ('nitrogen', models.FloatField()),
                ('phosphorous', models.FloatField()),
                ('potassium', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('temperature', models.FloatField()),
                ('crop', models.CharField(max_length=100)),
            ],
        ),
    ]
