# Generated by Django 5.0.6 on 2024-06-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishimitra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='croprecommendation',
            old_name='phosphorous',
            new_name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='phosphorous',
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='phosphorus',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='nitrogen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='ph',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='potassium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='rainfall',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='temperature',
            field=models.CharField(max_length=100),
        ),
    ]
