# Generated by Django 5.0.6 on 2024-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishimitra', '0003_croprecommendation_date_croprecommendation_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('yield1', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('rainfall', models.CharField(max_length=100)),
                ('fertilizer', models.CharField(max_length=100)),
                ('fertilizerQty', models.CharField(max_length=100)),
                ('pesticide', models.CharField(max_length=100)),
                ('pesticideQty', models.CharField(max_length=100)),
                ('nitrogen', models.CharField(max_length=100)),
                ('phosphorus', models.CharField(max_length=100)),
                ('potassium', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=100)),
                ('soilColor', models.CharField(max_length=100)),
            ],
        ),
    ]
