# Generated by Django 5.0.6 on 2024-06-24 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishimitra', '0004_userdatainput'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatainput',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userdatainput',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
